import * as db from '@/lib/supabase-data'
import type { SchemaField } from '@/types/project'

type ToolFn = (params: Record<string, unknown>) => Promise<unknown>

/**
 * Maps MCP tool names → Supabase data layer (async).
 * All execution happens in-browser, calling Supabase directly.
 */
export const toolExecutors: Record<string, ToolFn> = {
  // ─── Projects ───────────────────────────────────────
  list_projects: () => db.listProjects(),

  get_project: ({ projectId }) => db.getProject(projectId as string),

  create_project: ({ name, description }) =>
    db.createProject(name as string, (description as string) ?? ''),

  update_project: async ({ projectId, ...updates }) => {
    return db.updateProject(projectId as string, updates)
  },

  delete_project: async ({ projectId }) => {
    await db.deleteProject(projectId as string)
    return { ok: true }
  },

  // ─── Tables ─────────────────────────────────────────
  list_tables: ({ projectId }) => db.listSchemas(projectId as string),

  get_table: ({ tableId }) => db.getSchema(tableId as string),

  create_table: ({ projectId, name, columns, mode }) =>
    db.createSchema(
      projectId as string,
      name as string,
      (columns as SchemaField[]) ?? [],
      (mode as 'data' | 'config') ?? 'data',
    ),

  rename_table: ({ tableId, name }) =>
    db.renameSchema(tableId as string, name as string),

  delete_table: async ({ tableId }) => {
    await db.deleteSchema(tableId as string)
    return { ok: true }
  },

  // ─── Columns ────────────────────────────────────────
  add_column: ({ tableId, name, type, required, values, configRef }) => {
    const field: SchemaField = {
      name: name as string,
      type: type as SchemaField['type'],
      required: (required as boolean) ?? false,
      ...(values ? { values: values as string[] } : {}),
      ...(configRef ? { configRef: configRef as string } : {}),
    }
    return db.addColumn(tableId as string, field)
  },

  update_column: ({ tableId, columnName, ...updates }) =>
    db.updateColumn(tableId as string, columnName as string, updates as Partial<SchemaField>),

  remove_column: ({ tableId, columnName }) =>
    db.removeColumn(tableId as string, columnName as string),

  // ─── Rows ───────────────────────────────────────────
  list_rows: ({ tableId }) => db.listEntries(tableId as string),

  get_row: ({ rowId }) => db.getEntry(rowId as string),

  add_row: ({ tableId, data, environment }) =>
    db.createEntry(
      tableId as string,
      data as Record<string, unknown>,
      (environment as 'development' | 'staging' | 'production') ?? 'development',
    ),

  update_row: ({ rowId, data }) =>
    db.updateEntry(rowId as string, data as Record<string, unknown>),

  delete_row: async ({ rowId }) => {
    await db.deleteEntry(rowId as string)
    return { ok: true }
  },

  // ─── Versions ───────────────────────────────────────
  list_versions: ({ projectId }) => db.listVersions(projectId as string),

  publish_version: ({ projectId, environment }) =>
    db.publishVersion(
      projectId as string,
      environment as 'development' | 'staging' | 'production',
    ),

  promote_version: ({ versionId, targetEnvironment }) =>
    db.promoteVersion(
      versionId as string,
      targetEnvironment as 'development' | 'staging' | 'production',
    ),

  rollback_version: async ({ versionId }) => {
    await db.rollbackVersion(versionId as string)
    return { ok: true }
  },

  delete_version: async ({ versionId }) => {
    await db.deleteVersion(versionId as string)
    return { ok: true }
  },

  compare_versions: ({ versionId1, versionId2 }) =>
    db.compareVersions(versionId1 as string, versionId2 as string),

  // ─── Activity ───────────────────────────────────────
  list_activity: ({ projectId }) => db.listActivity(projectId as string),

  // ─── Codegen ────────────────────────────────────────
  generate_csharp_code: async ({ projectId }) => {
    const schemas = await db.listSchemas(projectId as string)
    if (schemas.length === 0) return { code: '// No tables found' }

    let code = '// Auto-generated by Unity Flux\n'
    code += 'using UnityEngine;\nusing System;\n\n'

    for (const schema of schemas) {
      code += `[Serializable]\npublic class ${schema.name}\n{\n`
      for (const field of schema.fields) {
        const csType = ({ string: 'string', integer: 'int', float: 'float', boolean: 'bool', enum: 'string', list: 'string[]', color: 'string', config: 'string' } as Record<string, string>)[field.type] ?? 'string'
        const fieldName = '_' + field.name.charAt(0).toLowerCase() + field.name.slice(1)
        const propName = field.name.charAt(0).toUpperCase() + field.name.slice(1)
        code += `    [SerializeField] private ${csType} ${fieldName};\n`
        code += `    public ${csType} ${propName} => ${fieldName};\n\n`
      }
      code += '}\n\n'
    }

    return { code }
  },
}
