import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'
import type { JsonStore } from '../store/json-store.js'

const TYPE_MAP: Record<string, string> = {
  string: 'string',
  integer: 'int',
  float: 'float',
  boolean: 'bool',
  enum: 'string',
  list: 'List<string>',
  color: 'Color',
  config: 'string',
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, ch) => ch.toUpperCase())
    .replace(/^[a-z]/, (ch) => ch.toUpperCase())
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function generateClass(schema: any, namespace: string): string {
  const className = toPascalCase(schema.name)
  const fields = schema.fields || []
  const isConfig = schema.mode === 'config'

  const lines: string[] = []
  lines.push(`    [Serializable]`)

  if (isConfig) {
    lines.push(`    public class ${className} : FluxConfigTable`)
  } else {
    lines.push(`    public class ${className}`)
  }

  lines.push(`    {`)

  for (const field of fields) {
    const csType = TYPE_MAP[field.type] || 'string'
    const fieldName = toCamelCase(field.name)
    const propName = toPascalCase(field.name)

    if (field.type === 'enum' && field.values && field.values.length > 0) {
      lines.push(`        // Enum values: ${field.values.join(', ')}`)
    }

    if (field.type === 'config' && field.configRef) {
      lines.push(`        // References config table: ${field.configRef}`)
    }

    lines.push(`        [SerializeField] private ${csType} ${fieldName};`)
    lines.push(`        public ${csType} ${propName} => ${fieldName};`)
    lines.push(``)
  }

  lines.push(`    }`)

  return lines.join('\n')
}

function generateLoaderClass(): string {
  const lines: string[] = []
  lines.push(`    /// <summary>`)
  lines.push(`    /// Utility class for loading and caching Unity Flux configurations.`)
  lines.push(`    /// </summary>`)
  lines.push(`    public static class FluxLoader`)
  lines.push(`    {`)
  lines.push(`        private static readonly Dictionary<string, object> _cache = new Dictionary<string, object>();`)
  lines.push(``)
  lines.push(`        public static T Load<T>(string path) where T : class`)
  lines.push(`        {`)
  lines.push(`            if (_cache.TryGetValue(path, out var cached))`)
  lines.push(`                return cached as T;`)
  lines.push(``)
  lines.push(`            var json = Resources.Load<TextAsset>(path);`)
  lines.push(`            if (json == null)`)
  lines.push(`                throw new System.IO.FileNotFoundException($"Config not found at: {path}");`)
  lines.push(``)
  lines.push(`            var result = JsonUtility.FromJson<T>(json.text);`)
  lines.push(`            _cache[path] = result;`)
  lines.push(`            return result;`)
  lines.push(`        }`)
  lines.push(``)
  lines.push(`        public static T[] LoadArray<T>(string path)`)
  lines.push(`        {`)
  lines.push(`            var json = Resources.Load<TextAsset>(path);`)
  lines.push(`            if (json == null)`)
  lines.push(`                throw new System.IO.FileNotFoundException($"Config not found at: {path}");`)
  lines.push(``)
  lines.push(`            return JsonUtility.FromJson<FluxArrayWrapper<T>>(json.text).items;`)
  lines.push(`        }`)
  lines.push(``)
  lines.push(`        public static void ClearCache()`)
  lines.push(`        {`)
  lines.push(`            _cache.Clear();`)
  lines.push(`        }`)
  lines.push(``)
  lines.push(`        [Serializable]`)
  lines.push(`        private class FluxArrayWrapper<T>`)
  lines.push(`        {`)
  lines.push(`            public T[] items;`)
  lines.push(`        }`)
  lines.push(`    }`)
  return lines.join('\n')
}

export function registerCodegenTools(server: McpServer, store: JsonStore) {
  server.tool(
    'generate_csharp',
    'Generate C# data classes for all schemas in a project',
    {
      projectId: z.string(),
      namespace: z.string().optional().default('GameConfig'),
    },
    async ({ projectId, namespace }) => {
      try {
        const schemas = store.listSchemas(projectId)

        if (schemas.length === 0) {
          return {
            content: [{ type: 'text' as const, text: 'No schemas found in this project. Create tables first.' }],
          }
        }

        const lines: string[] = []
        lines.push(`// Auto-generated by Unity Flux MCP Server`)
        lines.push(`// Do not edit manually — changes will be overwritten on next generation.`)
        lines.push(``)
        lines.push(`using System;`)
        lines.push(`using System.Collections.Generic;`)
        lines.push(`using UnityEngine;`)
        lines.push(``)
        lines.push(`namespace ${namespace}`)
        lines.push(`{`)

        const configSchemas = schemas.filter((s: any) => s.mode === 'config')
        if (configSchemas.length > 0) {
          lines.push(`    /// <summary>`)
          lines.push(`    /// Base class for config-mode tables.`)
          lines.push(`    /// </summary>`)
          lines.push(`    [Serializable]`)
          lines.push(`    public abstract class FluxConfigTable`)
          lines.push(`    {`)
          lines.push(`        [SerializeField] private string id;`)
          lines.push(`        public string Id => id;`)
          lines.push(`    }`)
          lines.push(``)
        }

        for (let i = 0; i < schemas.length; i++) {
          lines.push(generateClass(schemas[i], namespace))
          if (i < schemas.length - 1) lines.push(``)
        }

        lines.push(``)
        lines.push(generateLoaderClass())
        lines.push(`}`)
        lines.push(``)

        const code = lines.join('\n')

        return { content: [{ type: 'text' as const, text: code }] }
      } catch (e) {
        return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true }
      }
    },
  )
}
